name: "Setup Omni"
description: "Install and cache omni CLI across platforms"
author: "omni-oss"
inputs:
  github-token:
    description: "GitHub token"
    required: false
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - name: Cache omni installation
      uses: actions/cache@v4
      with:
        path: ${{ runner.os == 'Windows' && '${{ env.LOCALAPPDATA }}\omni\bin' || '$HOME/.omni/bin' }}
        key: ${{ runner.os }}-omni-cli-binary
        restore-keys: |
          ${{ runner.os }}-omni-cli-binary

    - name: Install omni (Linux/macOS)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        export GITHUB_TOKEN="${{ inputs.github-token }}"
        curl -fsSL https://raw.githubusercontent.com/omni-oss/omni/main/installers/unix.sh | sh

    - name: Install omni (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $env:GITHUB_TOKEN = "${{ inputs.github-token }}"
        curl -fsSL https://raw.githubusercontent.com/omni-oss/omni/main/installers/windows.ps1 | powershell

    - name: Add omni to PATH (Linux/macOS)
      if: runner.os != 'Windows'
      shell: bash
      run: echo "$HOME/.omni/bin" >> $GITHUB_PATH

    - name: Add omni to PATH (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $installDir = "$env:LOCALAPPDATA\omni"
        $binDir = "$installDir\bin"
        "$binDir" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Verify omni
      shell: bash
      run: omni --version
